name: Test

on:
  pull_request:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  Test:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: 💾 Check out repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v3 # WARNING: This must be v3
    - name: ✨ Install pre-commit
      uses: pre-commit/action@v3.0.1
    - name: 🔥 Test
      run: pre-commit run --show-diff-on-failure --all-files

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
